kind: pipeline
name: default

steps:
- name: build
  image: openjdk:8-jdk
  commands:
  - chmod +x ./gradlew
  - ./gradlew clean build

- name: docker
  image: plugins/docker
  settings:
    repo: parag3gwl/spring
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy_master
  image: vallard/drone-kube
  settings:
    template: kubernetes/deployment.yml
    namespace: default
    server: https://34.68.50.92
    ca:
      from_secret: kube_ca
    token: token
  when:
      event:
      - push
      - pull-request
      branch:
      - deploy
